apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ingress
  name: nginx-ingress
spec:
  rules:
  - host: testear.awesomehost.com.br
    http:
      paths:
      - backend:
          serviceName: nginx-ingress
          servicePort: 18080
        path: /nginx_status