apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
  labels:
    run: airflow-webserver
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    run: airflow-webserver
---    
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: airflow-webserver
  namespace: airflow
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: testear.awesomehost.com.br
      http:
        paths:
          - path: /teste
            backend:
              serviceName: airflow-webserver
              servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: airflow
  name: airflow-webserver
  labels:
    name: airflow-webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: webserver
          image: xxxx.dkr.ecr.us-east-1.amazonaws.com/airflow:latest
          ports:
            - containerPort: 8080
          command: ["airflow"]
          args: ["webserver"]
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"

